# Generated by Django 4.2.7 on 2023-12-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='faculty',
        ),
        migrations.AddField(
            model_name='administration',
            name='contact_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
